# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Proxy Update Job

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'

permissions:
    contents: read
    pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.16.0]

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - run: npm i
    - run: npm install -g protractor
    - run: sudo chmod 0755 /usr/local/share/chromedriver-linux64
    - run: protractor conf.js
    - name: Commit files
      run: |
        git config --local user.email "418160487326+Skiddle-Git@users.noreply.github.com"
        git config --local user.name "Skiddle Git Assistant"
        git commit -a -m "Updated Proxies"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.BOT_GITHUB_TOKEN }}
        branch: ${{ github.ref }}
      env:
        CI: true
